### PR TITLE
Deno v1.31.0

### PR DESCRIPTION
**Pull request by SpencerIsGiddy**
Update to deno v1.31.0

the only thing worth mentioning with this update is that std/node is now apart of deno according to v1.178.0 so those can be removed from import map (I believe)

### CODE REVIEW

**Comment by GiddyGoatGaming** [comment]
It seems to want to throw up this error when deploying with 1.178.0.

Error The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@0.178.0/node/buffer.ts)

 When I remove it from import map, it says something like prefix not found or something (can’t remember what exactly). Should we use 1.177.0 until we figure out what to do?

**Comment by ignoramous** [comment]
> Should we use 1.177.0 until we figure out what to do?

Sounds good to me.

**Review by timsbasset — COMMENTED** [review]
good

**Comment by timsbasset** [comment]
hope its working

**Pull request closed without merging**
