### PR TITLE
only heartbeat if there is data in the payload

### LINKED ISSUE #146: fly.io checks trigger heartbeat so machine never stops
Thank you for your work on this.  I was tinkering with getting this to work with fly.io's machines functionality so that way I could have my instance scale to 0 when I'm not using it.  In attempting to get the machines to scale to 0, I noticed that the calls to the /check endpoint triggered the machinesHeartbeat function which kept the machine running which prevented the auto scaling from scaling it to 0.

I think I have a fix for this and will submit a PR momentarily.

### PR DESCRIPTION
**Pull request by MarkIannucci**
fixes #146

### CODE REVIEW

**Comment by ignoramous** [comment]
But the `/checks` endpoint is on port 8888? `serveTCP` is never called by the server socket listening on 8888.

**Comment by MarkIannucci** [comment]
I was puzzled by that as well.  My fork has a commit with a repro of what I was seeing in it.  I'll uncover it later tonight and post back with an update.

**Comment by ignoramous** [comment]
I think you might be right about health checks, but it might be the *TCP* checks:

https://github.com/serverless-dns/serverless-dns/blob/ea7e83b4253784cfb71ccf111d8e258ef5ea92ed/fly.machines.toml#L60-L64

Two options:

- Remove TCP checks for Machines (`fly.machines.tls.toml` and `fly.machines.toml`). Rely on custom checks on port 8888.
- Don't heartbeat unless there's data.

**Comment by MarkIannucci** [comment]
My gut says both.  I think avoiding the heartbeat when the app gets an empty payload may be helpful in dealing with the DOS problems Rethink sometimes faces, beyond my accidental fix of the zero scaling.  

As for the health check, I'd lean solely on the custom checks for health to verify health for the fly platform. These can also be useful for external service health monitoring.

I'll follow up with a second PR to remove the tcp checks from the toml files.

**Comment by ignoramous** [comment]
Merged. Thanks!

**Pull request merged**
