### PR TITLE
Add <> formatting to tls readme, fix settings.json error and update wrangler to support the latest compatibility date

### PR DESCRIPTION
**Pull request by SpencerIsGiddy**
I know the .vscode file is not used in production but there is an error which this fixes. Validated by jsonlint.com / json validator.

Also adds <> formatting to the tls formatting just for good practices

### CODE REVIEW

**Comment by SpencerIsGiddy** [comment]
Just added a change to the compatibility date on the cloudflare worker. The change is found [here] (https://developers.cloudflare.com/workers/platform/compatibility-dates/)

**Comment by SpencerIsGiddy** [comment]
I cannot figure out why the error is occuring. it seems right to me and i tried troubleshooting the error and have not found an actual answer.

I just made a test commit where i upgrade the webpack to es2022 since workers got an update to that in February but that did not fix the error.

**Comment by ignoramous** [comment]
The error seems unrelated to your patches...

**Comment by SpencerIsGiddy** [comment]
Would you want me to revert webpack for workers to es2020 or keep es2022?

**Comment by ignoramous** [comment]
Is `es2022` a valid target for Node v19? I've checked for Workers and it supports es2022.

**Comment by SpencerIsGiddy** [comment]
I would assume [so](https://kangax.github.io/compat-table/es2016plus/) and [this even though it mentions typescript](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping)

**Review by ignoramous — APPROVED** [review]

**Comment by ignoramous** [comment]
Thanks.

**Pull request merged**
